/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:b497c765-9db7-4dbe-8d58-5b0608f7404c",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_W8r0RkbIn",
    "aws_user_pools_web_client_id": "6s8rgbglnusslmnt3ks4oln7fo",
    "oauth": {},
    "aws_cognito_login_mechanism": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_appsync_graphqlEndpoint": "https://sb4orisxebdxldmjw2poebgmma.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jgrstdoosndjnfndp7i7ygzu34"
};


export default awsmobile;
